### PR TITLE
Initial Python3 update

### PR DESCRIPTION
**Pull request by Lewiscowles1986**
* removed psyco (it's pypy now & not an import)
 * changed `range(...)` to `list(range(...))`
 * fixed `print` calls by adding parenthesis
 * Adjusted `CPickle` reference to `_pickle`
 * cast a few vars to `int`

### CODE REVIEW

**Comment by Lewiscowles1986** [comment]
fixes #1 probably needs tests to ensure works 100%

**Comment by chozabu** [comment]
@Lewiscowles1986  :+1: I've merged this, and added a requirements.txt to make setup easier
Will try and merge quicker in the future if you have any more updates ;)

**Comment by Lewiscowles1986** [comment]
Thanks :+1: 

Raise some issues, I'll watch the repo see if I can help with anything

**Comment by chozabu** [comment]
Well - there are loads of things:
-Need a decent menu
-Level browser/Selector
-check networking, _should_ be OK - but not sure I trust me from ~8 years ago!
-lan game broadcast/discovery
-internet server browser?
-balance weapons
-more weapons
-more visual themes (seems I part wrote a system to support multiple themes)
-driveable vehicles (This could work well with the destructable terrain, but may be hard to make perform well)
-code cleanup
-optimisation
-pypy compatibility?
-mobile support ;)
-thinking of more changes and upgrades

I'll break some of this down into issues

**Pull request merged**
